name: flutter_next
description: A flutter package for faster UI developement and provide
  responsiveness for flutter web applications and has multiple extensions.
version: 0.0.7
homepage: https://shashiben.github.io
repository: https://github.com/shashiben/flutter_next
issue_tracker: https://github.com/shashiben/flutter_next/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.0.4
  visibility_detector: ^0.2.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
