name: one_page
description: Clone of a bootstrap template from bootstrap_made website in flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"

dependencies:
  carousel_slider: null
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  go_router: ^3.0.1
  line_icons: ^2.0.1
  simple_animations: ^4.0.1
  universal_html: ^2.0.8
  universal_platform: ^1.0.0+1
  visibility_detector: ^0.2.2
  webviewx: ^0.2.1
  animations:
  flutter_next:

dev_dependencies:
  flutter_lints: ^1.0.0
  build_runner: ^1.0.0
  preload: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/clients/
    - assets/portfolio/
    - assets/team/
    - assets/testimonials/
    - assets/fonts/

  fonts:
    - family: Opensans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
